version: "2.3" # v2.3 because: Remove unsupported IPAM config entries in v3

services:
    admin_host:
        build: ./admin_host/
        container_name: admin_host
        hostname: admin_host
        env_file:
            - ./.env
        volumes:
            - ./ssh_pub:/var/ssh_pub
            - ./ansible:/home/admin/ansible
        networks:
            app_net:
                ipv4_address: 172.16.1.2
        tty: true # possible login to your container using TTY without running SSH server or other

    client_host_01:
        build: ./client_host/
        container_name: client_host_01
        hostname: client_host_01
        volumes:
            - ./ssh_pub:/var/ssh_pub
        depends_on:
            - admin_host
        networks:
            app_net:
                ipv4_address: 172.16.1.3
        ports:
            - 8081:80 #nginx

    client_host_02:
        build: ./client_host/
        container_name: client_host_02
        hostname: client_host_02
        volumes:
            - ./ssh_pub:/var/ssh_pub
        depends_on:
            - admin_host
        networks:
            app_net:
                ipv4_address: 172.16.1.4
        ports:
            - 8082:80 #nginx

    client_host_03:
        build: ./client_host/
        container_name: client_host_03
        hostname: client_host_03
        volumes:
            - ./ssh_pub:/var/ssh_pub
        depends_on:
            - admin_host
        networks:
            app_net:
                ipv4_address: 172.16.1.5
        ports:
            - 8083:80 #nginx


networks:
    app_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.16.1.0/24"
                  gateway: "172.16.1.1"