version: "2.3" # v2.3 because: Remove unsupported IPAM config entries in v3

services:
    admin-host:
        build: ./admin-host/
        container_name: admin-host
        hostname: admin-host
        env_file:
            - ./.env
        volumes:
            - ./ssh_pub:/var/ssh_pub
            - ./ansible:/home/admin/ansible
        networks:
            app_net:
                ipv4_address: 172.16.1.2
        tty: true # possible login to your container using TTY without running SSH server or other

    client-host-01:
        build: ./client-host/
        container_name: client-host-01
        hostname: client-host-01
        volumes:
            - ./ssh_pub:/var/ssh_pub
        depends_on:
            - admin-host
        networks:
            app_net:
                ipv4_address: 172.16.1.3
        ports:
            - 8081:80 #nginx

    client-host-02:
        build: ./client-host/
        container_name: client-host-02
        hostname: client-host-02
        volumes:
            - ./ssh_pub:/var/ssh_pub
        depends_on:
            - admin-host
        networks:
            app_net:
                ipv4_address: 172.16.1.4
        ports:
            - 8082:80 #nginx

    client-host-03:
        build: ./client-host/
        container_name: client-host-03
        hostname: client-host-03
        volumes:
            - ./ssh_pub:/var/ssh_pub
        depends_on:
            - admin-host
        networks:
            app_net:
                ipv4_address: 172.16.1.5
        ports:
            - 8083:80 #nginx


networks:
    app_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.16.1.0/24"
                  gateway: "172.16.1.1"