---

- name: "Install MYSQL"
  ansible.builtin.apt:
    name: "mysql-server"
    state: "latest"
    update-cache: true

- name: "Install pymysql"
  ansible.builtin.apt:
    name: "python3-pymysql"
    state: "latest"
    update-cache: true

- name: "Start myslq"
  shell: "/etc/init.d/mysql start" # service not work in docker-container

- name: "Set up user"
  community.mysql.mysql_user:
    name: "{{ lookup('env', 'MYSLQ_DEFAULT_USER') }}"
    password: "{{ lookup('env', 'MYSQL_DEFAUL_PASSWORD') }}"
    priv: "*.*:ALL"
    login_user: "{{ lookup('env', 'MYSLQ_DEFAULT_USER') }}"
    login_password: "{{ lookup('env', 'MYSQL_DEFAUL_PASSWORD') }}"
    check_implicit_admin: true
    login_unix_socket: "/var/run/mysqld/mysqld.sock"

- name: "Remove anon-users"
  community.mysql.mysql_user:
    name: ""
    state: "absent"
    login_user: "{{ lookup('env', 'MYSLQ_DEFAULT_USER') }}"
    login_password: "{{ lookup('env', 'MYSQL_DEFAUL_PASSWORD') }}"