---

- name: "Install PostgreSQL"
  ansible.builtin.apt: 
    name: "{{ item }}"
    update_cache: true
    state: "present"
  loop:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python3-psycopg2

- name: "Start PostgreSQL"
  ansible.builtin.service:
    name: "postgresql"
    state: "started"
    enabled: true

- name: "Create a new database"
  become: "yes"
  become_user: "postgres"
  postgresql_db:
    name: "{{postgresql_db_name}}"
    encoding: "UTF-8"
    template: "template0"

- name: "Add user for db"
  become: "yes"
  become_user: "postgres"
  postgresql_user:
    db: "{{postgresql_db_name}}"
    name: "{{ lookup('env', 'POSTGRESQL_USER') }}"
    password: "{{ lookup('env', 'POSTGRESQL_PASSWORD') }}"
    priv: "ALL"
    role_attr_flags: "CREATEDB,NOSUPERUSER"
